### ISSUE TITLE
Having trouble installing

### ISSUE THREAD

**Issue by johnjacobkenny** [4Catalyzer/karma-jest#28]
Further to our discussion in #26 (https://github.com/4Catalyzer/karma-jest/pull/26#issuecomment-626418756) I was trying to create the example project. I'm getting this error.

![image](https://user-images.githubusercontent.com/19240564/81526316-e4108a00-9374-11ea-8c90-2d52c2c8e736.png)

**Comment by jquense** [comment]
Looks like you are installing an older beta can you try `npm install karma-jest@next` to get the latest and this should be fixed

**Comment by johnjacobkenny** [comment]
Yep! That worked.
